# Generated by Django 5.2.4 on 2025-07-21 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=10)),
                ('member_class', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'history_member',
            },
        ),
        migrations.CreateModel(
            name='PlayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_type_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'history_play_type',
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=20)),
                ('role_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history_staff_role',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_name', models.CharField(max_length=50)),
                ('play_date', models.DateField(null=True)),
                ('play_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='history.playtype')),
            ],
            options={
                'db_table': 'history_play',
            },
        ),
        migrations.CreateModel(
            name='MemberRoleMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_play', models.CharField(blank=True, max_length=50, null=True)),
                ('is_actor', models.BooleanField(default=False)),
                ('actor_role', models.CharField(blank=True, max_length=50, null=True)),
                ('actor_description', models.TextField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='history.member')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.play')),
                ('staff_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='history.staffrole')),
            ],
            options={
                'db_table': 'history_member_role_match',
                'constraints': [models.UniqueConstraint(fields=('member', 'staff_role'), name='unique_member_staff_role')],
            },
        ),
    ]
