# Generated by Django 5.2.4 on 2025-07-26 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=10)),
                ('member_class', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'history_member',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_name', models.CharField(max_length=50)),
                ('play_date', models.DateField(null=True)),
                ('play_summary', models.TextField(null=True)),
            ],
            options={
                'db_table': 'history_play',
            },
        ),
        migrations.CreateModel(
            name='PlayCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_character_name', models.CharField(max_length=100)),
                ('play_character_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history_play_character',
            },
        ),
        migrations.CreateModel(
            name='PlayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_type_name', models.CharField(max_length=30)),
                ('play_type_description', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'history_play_type',
            },
        ),
        migrations.CreateModel(
            name='StaffRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_role_name', models.TextField()),
                ('staff_role_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history_staff_role',
            },
        ),
        migrations.CreateModel(
            name='MemberSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_summary_created', models.DateTimeField(auto_now_add=True)),
                ('member_summary', models.TextField(null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.member')),
            ],
            options={
                'db_table': 'history_member_summary',
            },
        ),
        migrations.CreateModel(
            name='PlayScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_name', models.TextField()),
                ('script_author', models.TextField()),
                ('script_created', models.DateField(blank=True, null=True)),
                ('script_description', models.TextField(blank=True, null=True)),
                ('script_member_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.member')),
            ],
            options={
                'db_table': 'history_play_script',
            },
        ),
        migrations.CreateModel(
            name='PlaySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_summary_created', models.DateTimeField(auto_now_add=True)),
                ('play_summary', models.TextField(null=True)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.play')),
            ],
            options={
                'db_table': 'history_play_summary',
            },
        ),
        migrations.AddField(
            model_name='play',
            name='play_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.playtype'),
        ),
        migrations.CreateModel(
            name='PlayTypeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('play_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.playtype')),
            ],
            options={
                'db_table': 'history_play_type_alias',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.member')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.play')),
                ('play_character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.playcharacter')),
                ('play_script', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.playscript')),
                ('staff_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.staffrole')),
            ],
            options={
                'db_table': 'history_participation',
            },
        ),
    ]
