# Generated by Django 5.2.4 on 2025-07-26 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='play_date',
        ),
        migrations.CreateModel(
            name='PlayDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_date', models.DateTimeField(blank=True, null=True)),
                ('play_location', models.TextField(blank=True, null=True)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.play')),
            ],
            options={
                'db_table': 'history_play_date',
            },
        ),
    ]
