# Generated by Django 5.2.4 on 2025-07-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_remove_play_play_date_playdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='play_summary',
            new_name='play_description',
        ),
    ]
