# Generated by Django 5.2.4 on 2025-07-27 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_rename_play_summary_play_play_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='play_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='history.playtypealias'),
        ),
    ]
